"""add Department

Revision ID: 197ccb2e858a
Revises: a9fe58f96c58
Create Date: 2025-06-12 19:36:14.538801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197ccb2e858a'
down_revision = 'a9fe58f96c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
